<?php
$quote = $block->getQuote();

$iPod    = stripos($_SERVER['HTTP_USER_AGENT'],"iPod");
$iPhone  = stripos($_SERVER['HTTP_USER_AGENT'],"iPhone");
$iPad    = stripos($_SERVER['HTTP_USER_AGENT'],"iPad");
$Android = stripos($_SERVER['HTTP_USER_AGENT'],"Android");

$device = '';
?>

<?php if($iPod): ?>
	<?php $device = 'iPod'; ?>
<?php elseif($iPhone): ?>
	<?php $device = 'iPhone'; ?>
<?php elseif($iPad): ?>
	<?php $device = 'iPad'; ?>
<?php elseif($Android): ?>
	<?php $device = 'Android'; ?>
<?php else: ?>
    <?php $device = 'Web'; ?>				
<?php endif; ?>

<?php $quote->setDevice($device)->save(); ?>